// Export all models for easy importing
export { default as User } from "./User"
export { default as Product } from "./Product"
export { default as Category } from "./Category"
export { default as Order } from "./Order"
export { default as Review } from "./Review"
export { default as Cart } from "./Cart"
export { default as Wishlist } from "./Wishlist"
export { default as Coupon } from "./Coupon"
export { default as Analytics } from "./Analytics"
export { default as Notification } from "./Notification"
export { default as Settings } from "./Settings"
export { default as SearchHistory } from "./SearchHistory"
export { default as Inventory } from "./Inventory"

// Export types
export type { IUser, IAddress } from "./User"
export type { IProduct, IProductVariant } from "./Product"
export type { ICategory } from "./Category"
export type { IOrder, IOrderItem, ITrackingEvent } from "./Order"
export type { IReview } from "./Review"
export type { ICart, ICartItem } from "./Cart"
export type { IWishlist, IWishlistItem } from "./Wishlist"
export type { ICoupon } from "./Coupon"
export type { IAnalytics } from "./Analytics"
export type { INotification } from "./Notification"
export type { ISettings } from "./Settings"
export type { ISearchHistory } from "./SearchHistory"
export type { IInventory, IInventoryMovement } from "./Inventory"
